apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sqlserver2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: sqlserver2
        image: mcr.microsoft.com/mssql/server:2019-CTP2.4-ubuntu
        ports:
        - containerPort: 1433
        env:
        - name: SA_PASSWORD
          value: "Testing1122"
        - name: ACCEPT_EULA
          value: "Y"
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-data