apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-systemdata
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mssql-storage
  resources:
    requests:
      storage: 1Gi