apiVersion: v1
kind: Service
metadata:
  name: mssql-hl-service
  labels:
    app: mssql
spec:
  ports:
  - port: 80
  clusterIP: None
  selector:
    app: mssql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
spec:
  selector:
    matchLabels:
      app: mssql
  serviceName: mssql-hl-service
  replicas: 1 
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: sqlserver1
        image: mcr.microsoft.com/mssql/server:2019-CTP2.5-ubuntu
        ports:
        - containerPort: 1433
        env:
        - name: SA_PASSWORD
          value: "Testing1122"
        - name: ACCEPT_EULA
          value: "Y"
        volumeMounts:
        - name: mssql-system
          mountPath: /var/opt/mssql
  volumeClaimTemplates:
  - metadata:
      name: mssql-system
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "mssql-storage"
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  annotations: 
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  ports:
  - name: mssql
    port: 1433
    targetPort: 1433
  selector:
    app: mssql
  type: LoadBalancer